apiVersion: v1
kind: Pod
metadata:
  name: jg-app-pod
spec:
  containers:
    - name: jg-app-container
      image: 134986800938.dkr.ecr.us-east-1.amazonaws.com/jg-asg2-ecr:jg_app-v1
      ports:
        - containerPort: 80
#   imagePullSecrets:
#     - name: ecr-registry-key